--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImperaZim/EasyGroups
build-by-default: true
branches:
- v2.0
projects:
  EasyGroups:
    url: "metadata/groups_20230103054903.png"
...
