
# >======================< #

database:
 type: "YAML"
 
 mysql-provinder: 
  host: 0.0.0.0
  port: 3306
  user: EasyGroups
  password: user_admin
  db: EasyPlugins 
  
# >======================< #

group: 
 default: "guest"
 
 alert:
  enable: true
  only-vip: true
  message: ["{player}", "ยง7became {group}"]
  
# >======================< #
